services:
  postgres:
    image: postgres:18
    container_name: hotel-booking-postgres
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: hotelbooking
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/varadmin/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
volumes:
  postgres_data: